LibraryManagement/Areas/Admin/Controllers/BookController.cs
using LibraryManagement.Areas.Admin.Models.ViewModels;
using LibraryManagement.Models.Entity;
using LibraryManagement.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using MongoDB.Driver.Linq;
using MongoDbGenericRepository.Utils;
using System.Data;
using System.Linq;
using static System.Formats.Asn1.AsnWriter;

namespace LibraryManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Librarian")]
    public class BookController : Controller
    {
        protected DatabaseService dbService;

        public BookController(DatabaseService dbService)
        {
            this.dbService = dbService;
        }
        
        public IActionResult Index(bookIndexViewModel bookIndexVM)
        {            
            bookIndexVM.Books = dbService.bookCollection.AsQueryable<Book>().ToList();
            return View(bookIndexVM);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Book book, IFormFile Image)
        {
            if(book != null)
            {
                book.Available = book.Quantity;

                if(Image != null && Image.Length > 0)
                {
                    using (var target = new MemoryStream())
                    {
                        Image.CopyTo(target);
                        book.ImageContent = target.ToArray();
                    }
                }
                await dbService.CreateAsync(book);
                ViewBag.Message = "Book created successfully.";

                return RedirectToAction(nameof(BookController.Index), nameof(BookController).Replace("Controller", ""), new { area = "Admin" });
            }
            return NotFound();
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var filter = Builders<Book>.Filter.Eq(book => book.Id, id);
            var book = await dbService.bookCollection.Find(filter).FirstOrDefaultAsync();
            if (book == null)
            {
                return NotFound();
            }            

            return View(book);
        }

        public async Task<IActionResult> dataEdit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var filter = Builders<Book>.Filter.Eq(book => book.Id, id);
            var book = await dbService.bookCollection.Find(filter).FirstOrDefaultAsync();
            if (book == null)
            {
                return NotFound();
            }

            bookEditViewModel bookVM = new bookEditViewModel
            {
                Id = book.Id,
                Name = book.Name,
                Author = book.Author,
                Description = book.Description,
                Pages = book.Pages,
                Year = book.Year,
                ISBN = book.ISBN,
                Available = book.Available,
                Quantity = book.Quantity
            };

            return View(bookVM);
        }

        [HttpPost]
        public async Task<IActionResult> dataEdit(Guid? id, bookEditViewModel bookEditVM)
        {
            if (id == null || bookEditVM == null)
            {
                return NotFound();
            } 

            Book bookEdit = new Book()
            {
                Id = bookEditVM.Id,
                Name = bookEditVM.Name,
                Author = bookEditVM.Author,
                Description = bookEditVM.Description,
                Pages = bookEditVM.Pages,
                Year = bookEditVM.Year,
                ISBN = bookEditVM.ISBN,       
                Available = bookEditVM.Available,
                Quantity = bookEditVM.Quantity                
            };

            if (bookEdit == null)
            {
                return NotFound();
            }            

            if (ModelState.IsValid)
            {                
                var filter = Builders<Book>.Filter.Eq(book => book.Id, bookEdit.Id);
                // get data of original book
                Book book = await dbService.bookCollection.Find(filter).FirstOrDefaultAsync();
                // update available books
                
                // Quantity decrease
                if(book.Quantity > bookEdit.Quantity)
                {
                    book.Available = book.Available - (book.Quantity - bookEdit.Quantity);
                }
                // Quantity increase
                else if(book.Quantity < bookEdit.Quantity)
                {
                    book.Available = book.Available + (bookEdit.Quantity - book.Quantity);
                }
                
                var update = Builders<Book>.Update
                        .Set(b => b.Name, bookEdit.Name)
                        .Set(b => b.Author, bookEdit.Author)
                        .Set(b => b.Description, bookEdit.Description)
                        .Set(b => b.Pages, bookEdit.Pages)
                        .Set(b => b.Year, bookEdit.Year)
                        .Set(b => b.ISBN, bookEdit.ISBN)
                        .Set(b => b.Quantity, bookEdit.Quantity)
                        .Set(b => b.Available, book.Available);

                var result = await dbService.bookCollection.UpdateOneAsync(filter, update);
                if (result.IsAcknowledged)
                {
                    return RedirectToAction(nameof(BookController.Index), nameof(BookController).Replace("Controller", ""), new { area = "Admin" });
                }
                else
                {
                    // TODO: Add error view
                    return NotFound();
                }
            }

            var errors = ModelState.Values.SelectMany(v => v.Errors);
            foreach (var error in errors)
            {
                Console.WriteLine(error.ErrorMessage);
                ViewBag.ErrorMessage = error.ErrorMessage;
            }
            return View(bookEdit);
        }

        public async Task<IActionResult> imageEdit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var filter = Builders<Book>.Filter.Eq(book => book.Id, id);
            var book = await dbService.bookCollection.Find(filter).FirstOrDefaultAsync();
            if (book == null)
            {
                return NotFound();
            }

            imageEditViewModel imageVM = new imageEditViewModel
            {
                Id = book.Id,
                ImageContent = book.ImageContent,
                ImageAlt = book.ImageAlt
            };

            return View(imageVM);
        }

        [HttpPost]
        public async Task<IActionResult> imageEdit(Guid? id, IFormFile Image, imageEditViewModel imageEdit)
        {
            if (id == null || imageEdit == null)
            {
                return NotFound();
            }
            if (Image != null && Image.Length > 0)
            {
                using (var target = new MemoryStream())
                {
                    Image.CopyTo(target);
                    imageEdit.ImageContent = target.ToArray();
                }
            }

            if (ModelState.IsValid)
            {

                var filter = Builders<Book>.Filter.Eq(book => book.Id, imageEdit.Id);
                var update = Builders<Book>.Update
                        .Set(b => b.ImageContent, imageEdit.ImageContent)
                        .Set(b => b.ImageAlt, imageEdit.ImageAlt);
                        

                var result = await dbService.bookCollection.UpdateOneAsync(filter, update);
                if (result.IsAcknowledged)
                {
                    return RedirectToAction(nameof(BookController.Index), nameof(BookController).Replace("Controller", ""), new { area = "Admin" });
                }
                else
                {
                    // TODO: Add error view
                    return NotFound();
                }
            }

            var errors = ModelState.Values.SelectMany(v => v.Errors);
            foreach (var error in errors)
            {
                Console.WriteLine(error.ErrorMessage);
                ViewBag.ErrorMessage = error.ErrorMessage;
            }
            return View(imageEdit);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filter = Builders<Book>.Filter.Eq(book => book.Id, id);
            var result = await dbService.bookCollection.DeleteOneAsync(filter);

            if (result.DeletedCount == 1)
            {
                return RedirectToAction(nameof(BookController.Index), nameof(BookController).Replace("Controller", ""), new { area = "Admin" });
            }
            else
            {
                return ViewBag.ErrorMessage = "Book Delete Error!";
            }
        }
               
        public async Task<IActionResult> Search(bookIndexViewModel bookIndexVM)
        {
            if (bookIndexVM != null)
            {
                var builder = Builders<Book>.Filter;
                FilterDefinition<Book> filterName = builder.Empty;
                FilterDefinition<Book> filterYear = builder.Empty;
                FilterDefinition<Book> filterAuthor = builder.Empty;

                if (bookIndexVM.SearchBook != null)
                {
                    filterName = builder.Regex(b => b.Name, new BsonRegularExpression(bookIndexVM.SearchBook.Pascalize()));
                }
                if (bookIndexVM.SearchYear != 0 && bookIndexVM.SearchYear != null)
                {
                    filterYear = builder.Eq(b => b.Year, bookIndexVM.SearchYear);
                }

LibraryManagement/Areas/Admin/Controllers/DashboardController.cs
using LibraryManagement.Controllers;
using LibraryManagement.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using LibraryManagement.Models.Entity;
using LibraryManagement.Areas.Admin.Models.ViewModels;
using System.Text.Json;
using System.IO;
using MongoDB.Bson;
using System.Text;
using static System.Net.WebRequestMethods;

namespace LibraryManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Librarian")]
    public class DashboardController : Controller
    {
        protected DatabaseService dbService;
        public DashboardController(DatabaseService dbService)
        {
           this.dbService = dbService;
        }

        public IActionResult Index()
        {
            // TODO: Load only nesessary data (too slow rn)
            CompleteViewModel completeVM = new CompleteViewModel();
            DashboardViewModel dashboardVM = new DashboardViewModel();         
            
            completeVM.Books = dbService.bookCollection.AsQueryable<Book>().ToList();
            completeVM.Users = dbService.usersCollection.AsQueryable<User>().ToList();
            completeVM.Loans = dbService.loanCollection.AsQueryable<Loan>().ToList();

            dashboardVM.completeVM = completeVM;
            return View(dashboardVM);
        }

        public async Task<IActionResult> Export()
        {
            CompleteViewModel completeVM = new CompleteViewModel();
            completeVM.Books = dbService.bookCollection.AsQueryable<Book>().ToList();
            completeVM.Users = dbService.usersCollection.AsQueryable<User>().ToList();
            completeVM.Loans = dbService.loanCollection.AsQueryable<Loan>().ToList();

            if (completeVM != null)
            {
                string jsonData = JsonSerializer.Serialize(completeVM);
                var fileBytes = Encoding.ASCII.GetBytes(jsonData);
                return new FileContentResult(fileBytes, "text/plain")
                {
                    FileDownloadName = "export.json"
                };                            
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Import(IFormFile importData)
        {            
            if (importData.Length > 0)
            {
                string fileContent = null;
                using (var reader = new StreamReader(importData.OpenReadStream()))
                {
                    fileContent = reader.ReadToEnd();
                }
                if(fileContent != null)
                {
                    CompleteViewModel data = Newtonsoft.Json.JsonConvert.DeserializeObject<CompleteViewModel>(fileContent);

                    // Inserting objs one by one to allow duplicate handling
                    if(data.Users != null)
                    {
                        foreach(var user in data.Users)
                        {
                            try
                            {
                                // Add user to DB
                                await dbService.usersCollection.InsertOneAsync(user);
                            }
                            catch (Exception e)
                            {
                                continue;
                            }
                        }                     
                    }
                    else if (data.Books != null)
                    {
                        foreach (var book in data.Books)
                        {
                            try
                            {
                                // Add book to DB
                                await dbService.bookCollection.InsertOneAsync(book);
                            }
                            catch (Exception e)
                            {
                                continue;
                            }
                        }
                    }
                    if (data.Loans != null)
                    {
                        foreach (var loan in data.Loans)
                        {
                            try
                            {
                                // Add loan to DB
                                await dbService.loanCollection.InsertOneAsync(loan);
                            }
                            catch (Exception e)
                            {
                                continue;
                            }
                        }
                    }
                    return RedirectToAction(nameof(DashboardController.Index), nameof(DashboardController).Replace("Controller", ""), new { area = "Admin" });
                }                
            }
            return NotFound();
        }
    }
}

LibraryManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OpenLibrary</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryManagement.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body class="bg-surface-secondary">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OpenLibrary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Books">Books</a>
                        </li>                        
                        @{
                            if (User.Identity.IsAuthenticated == true && User.IsInRole("Librarian"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Book" asp-action="Index">Book Index</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Loan" asp-action="Index">Loans</a>
                                </li>
                            }

                            if (User.Identity.IsAuthenticated == true && User.IsInRole("Customer"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Customer" asp-controller="Customer" asp-action="Index">Profile</a>
                                </li>                                
                            }
                        }                                                           
                    </ul> 
                    @{
                        if (User.Identity.IsAuthenticated == false)
                        {
                            <ul class="navbar-nav navbar-right">
                                <li class="nav-item"><a class="nav-link text-dark" asp-area="Security" asp-controller="Account" asp-action="Register"><span class="glyphicon"></span> Sign Up</a></li>
                                <li class="nav-item"><a class="nav-link text-dark" asp-area="Security" asp-controller="Account" asp-action="Login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                            </ul>
                        }
                        else
                        {                           
                            <ul class="nav navbar-nav navbar-right">
                                <li class="nav-item dropdown">                                    
                                    <a class="dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                        Logged as @User.Identity.Name
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                        <li class="nav-item py-0"><a class="text-dark py-0 px-2" asp-area="Security" asp-controller="Account" asp-action="Logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                                    </ul>
                                </li>
                            </ul>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="py-6 mb-6">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-surface-primary text-muted">
        <div class="container">
            &copy; OpenLibrary | by Jan Sáblík & David Bilnica 2022
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>